In [8]:
import pandas as pd
import pickle
import datetime

In [80]:
ID = 4
RobotWatch = open('data/human-play-demo/014_FP_092024.pickle', 'rb')
demo_dict_RW = dict(pickle.load(RobotWatch))
df_RW = pd.DataFrame(demo_dict_RW)
df_RW

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,NumberOfDemos
environment_name,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,...,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,FlappyBird,20
condition,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,20
seed,813,814,815,816,817,818,819,820,821,822,...,824,825,826,827,828,829,830,831,832,20
steps,313,654,182,94,63,182,295,208,210,51,...,88,136,205,67,130,139,123,175,51,20
timestamps,"[1726867623.2882545, 1726867643.296171, 172686...","[1726867660.5206912, 1726867660.5226915, 17268...","[1726867695.0480647, 1726867695.0490074, 17268...","[1726867705.7223222, 1726867705.724308, 172686...","[1726867711.952135, 1726867711.954127, 1726867...","[1726867716.5927944, 1726867716.5947874, 17268...","[1726867727.2550502, 1726867727.2570553, 17268...","[1726867743.6451209, 1726867743.6476054, 17268...","[1726867755.6434999, 1726867755.6444724, 17268...","[1726867767.7414536, 1726867767.7434454, 17268...",...,"[1726867776.0750206, 1726867776.0780122, 17268...","[1726867781.9914289, 1726867781.994425, 172686...","[1726867790.3264685, 1726867790.329414, 172686...","[1726867802.1240337, 1726867802.1260235, 17268...","[1726867806.9437108, 1726867806.9457018, 17268...","[1726867814.9906385, 1726867814.9926395, 17268...","[1726867823.4798038, 1726867823.4827502, 17268...","[1726867831.1826432, 1726867831.1836402, 17268...","[1726867841.5066175, 1726867841.5086162, 17268...",20
timestamps_datetime,"[2024-09-20 21:27:03.288253906, 2024-09-20 21:...","[2024-09-20 21:27:40.520690918, 2024-09-20 21:...","[2024-09-20 21:28:15.048063964, 2024-09-20 21:...","[2024-09-20 21:28:25.722322021, 2024-09-20 21:...","[2024-09-20 21:28:31.952135010, 2024-09-20 21:...","[2024-09-20 21:28:36.592793945, 2024-09-20 21:...","[2024-09-20 21:28:47.255050049, 2024-09-20 21:...","[2024-09-20 21:29:03.645119873, 2024-09-20 21:...","[2024-09-20 21:29:15.643498779, 2024-09-20 21:...","[2024-09-20 21:29:27.741452881, 2024-09-20 21:...",...,"[2024-09-20 21:29:36.075020020, 2024-09-20 21:...","[2024-09-20 21:29:41.991427979, 2024-09-20 21:...","[2024-09-20 21:29:50.326468018, 2024-09-20 21:...","[2024-09-20 21:30:02.124032959, 2024-09-20 21:...","[2024-09-20 21:30:06.943710205, 2024-09-20 21:...","[2024-09-20 21:30:14.990637939, 2024-09-20 21:...","[2024-09-20 21:30:23.479802979, 2024-09-20 21:...","[2024-09-20 21:30:31.182642822, 2024-09-20 21:...","[2024-09-20 21:30:41.506617188, 2024-09-20 21:...",20
states,"[[1.0, 0.33203125, 0.52734375, 1.0, 0.0, 1.0, ...","[[1.0, 0.29296875, 0.48828125, 1.0, 0.0, 1.0, ...","[[1.0, 0.1953125, 0.390625, 1.0, 0.0, 1.0, 1.0...","[[1.0, 0.2734375, 0.46875, 1.0, 0.0, 1.0, 1.0,...","[[1.0, 0.33203125, 0.52734375, 1.0, 0.0, 1.0, ...","[[1.0, 0.29296875, 0.48828125, 1.0, 0.0, 1.0, ...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.33203125, 0.52734375, 1.0, 0.0, 1.0, ...","[[1.0, 0.3125, 0.5078125, 1.0, 0.0, 1.0, 1.0, ...",...,"[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.25390625, 0.44921875, 1.0, 0.0, 1.0, ...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...","[[1.0, 0.234375, 0.4296875, 1.0, 0.0, 1.0, 1.0...","[[1.0, 0.2734375, 0.46875, 1.0, 0.0, 1.0, 1.0,...","[[1.0, 0.234375, 0.4296875, 1.0, 0.0, 1.0, 1.0...","[[1.0, 0.21484375, 0.41015625, 1.0, 0.0, 1.0, ...",20
actions,"[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",...,"[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ...","[None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",20
rewards,"[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...",...,"[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...","[None, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,...",20
chosen_action_prob,"[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....",...,"[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....","[None, [1.0, 0.0], [1.0, 0.0], [1.0, 0.0], [1....",20
optimal_action_prob,"[None, [[tensor(25.9144), tensor(26.4670)]], [...","[None, [[tensor(24.6845), tensor(25.1085)]], [...","[None, [[tensor(22.5068), tensor(23.4124)]], [...","[None, [[tensor(24.2459), tensor(24.6560)]], [...","[None, [[tensor(25.9144), tensor(26.4670)]], [...","[None, [[tensor(24.6845), tensor(25.1085)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(25.9144), tensor(26.4670)]], [...","[None, [[tensor(25.3068), tensor(25.7558)]], [...",...,"[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(24.0271), tensor(24.2696)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...","[None, [[tensor(23.4776), tensor(23.9604)]], [...","[None, [[tensor(24.2459), tensor(24.6560)]], [...","[None, [[tensor(23.4776), tensor(23.9604)]], [...","[None, [[tensor(22.8981), tensor(23.6483)]], [...",20

In [79]:
# df_RW
n = df_RW["NumberOfDemos"]["seed"]
rest = df_RW[0]["timestamps"][0]
first = df_RW[0]["timestamps"][1]
last = df_RW[n-1]["timestamps"][-1]

demo_rest = 1726868032154.9302
demo_first = 1726868054867.801
demo_last = 1726868363960.604

print(first)
print(datetime.datetime.fromtimestamp(demo_rest/1000), datetime.datetime.fromtimestamp(demo_first/1000), datetime.datetime.fromtimestamp(demo_last/1000))
print(datetime.datetime.fromtimestamp(rest), datetime.datetime.fromtimestamp(first), datetime.datetime.fromtimestamp(last))

1726868057.112663
2024-09-20 17:33:52.154930 2024-09-20 17:34:14.867801 2024-09-20 17:39:23.960604
2024-09-20 17:33:56.864902 2024-09-20 17:34:17.112663 2024-09-20 17:39:23.721580

In [6]:
def create_time_dict(num, demo_dict):
    new_dict = {'floatTimestamps':[],
                'rewards':[],
                'chosen_actions': [],
                'optimal_actions': [],
                'dateTimestamps': [],
                'states':[]}

    for i in range(num):
        for j in range(len(demo_dict[i]['rewards'])):
            new_dict['floatTimestamps'].append(demo_dict[i]["timestamps"][j])
            new_dict['dateTimestamps'].append(demo_dict[i]["timestamps_datetime"][j])
            new_dict['rewards'].append(demo_dict[i]["rewards"][j])
            new_dict['chosen_actions'].append(demo_dict[i]["chosen_actions"][j])
            new_dict['optimal_actions'].append(demo_dict[i]["optimal_actions"][j])
            new_dict['states'].append(demo_dict[i]["states"][j])

    return new_dict

In [7]:
df = df_RW

num=df["NumberOfDemos"][0]
print(num)
new_dict = create_time_dict(num, df)

df = pd.DataFrame(new_dict)


# df = df.T
df.head(15)

30

,floatTimestamps,rewards,chosen_actions,optimal_actions,dateTimestamps,states
0,1.725832e+09,0.0,None,None,2024-09-08 21:46:03.826421875,"[1.3419548590699215, 0.7491004965443078, 0.534..."
1,1.725832e+09,-1.0,"[0.23917519, 0.99995446, -0.33233207, 0.25173852]","[0.23917519, 0.99995446, -0.33233207, 0.25173852]",2024-09-08 21:46:03.930425781,"[1.3488191302174575, 0.7798742744568427, 0.524..."
2,1.725832e+09,-1.0,"[0.06253714, 0.9999979, -0.53365195, 0.020199312]","[0.06253714, 0.9999979, -0.53365195, 0.020199312]",2024-09-08 21:46:04.045420898,"[1.3510242490793531, 0.8133188203086642, 0.507..."
3,1.725832e+09,-1.0,"[0.23467325, 0.9966554, -0.8372556, 0.19791864]","[0.23467325, 0.9966554, -0.8372556, 0.19791864]",2024-09-08 21:46:04.151423096,"[1.357577921112503, 0.8463515022138158, 0.4798..."
4,1.725832e+09,-1.0,"[0.2594596, 0.3937191, -0.9754717, 0.5718972]","[0.2594596, 0.3937191, -0.9754717, 0.5718972]",2024-09-08 21:46:04.257936035,"[1.3655655456909592, 0.8609663721925727, 0.447..."
5,1.725832e+09,-1.0,"[0.05249178, -0.9999769, -0.07853703, -0.12632...","[0.05249178, -0.9999769, -0.07853703, -0.12632...",2024-09-08 21:46:04.364933105,"[1.3678917553153593, 0.8312499253735086, 0.442..."
6,1.725832e+09,-1.0,"[0.058567528, -0.9999924, -0.15449189, -0.1189...","[0.058567528, -0.9999924, -0.15449189, -0.1189...",2024-09-08 21:46:04.471931885,"[1.3694600060651454, 0.7978017788125501, 0.438..."
7,1.725832e+09,-1.0,"[0.056536127, -0.9999974, -0.004267086, -0.087...","[0.056536127, -0.9999974, -0.004267086, -0.087...",2024-09-08 21:46:04.578933838,"[1.371125172431395, 0.765055638679629, 0.43796..."
8,1.725832e+09,-1.0,"[0.28296784, -0.9999969, -0.01576616, -0.13006...","[0.28296784, -0.9999969, -0.01576616, -0.13006...",2024-09-08 21:46:04.685936035,"[1.3793954043443697, 0.7317600991852011, 0.437..."
9,1.725832e+09,-1.0,"[0.36339918, -0.99999547, -0.03265864, -0.1181...","[0.36339918, -0.99999547, -0.03265864, -0.1181...",2024-09-08 21:46:04.794441895,"[1.3906170030377474, 0.6985576466036038, 0.436..."
10,1.725832e+09,-0.0,"[0.20494483, -0.99990636, 0.0145880515, -0.071...","[0.20494483, -0.99990636, 0.0145880515, -0.071...",2024-09-08 21:46:04.900955811,"[1.3973153619057144, 0.6653117330795355, 0.436..."
11,1.725832e+09,-0.0,"[-0.041053906, -0.11074267, -0.0035073077, 0.0...","[-0.041053906, -0.11074267, -0.0035073077, 0.0...",2024-09-08 21:46:05.009953125,"[1.396622036460878, 0.6594382886000654, 0.4365..."
12,1.725832e+09,-0.0,"[-0.0027591134, -0.11481976, -0.010079759, -0....","[-0.0027591134, -0.11481976, -0.010079759, -0....",2024-09-08 21:46:05.115955078,"[1.3963434667350385, 0.6558915096526908, 0.436..."
13,1.725832e+09,-0.0,"[-0.009007989, -0.060491096, -0.003306501, -0....","[-0.009007989, -0.060491096, -0.003306501, -0....",2024-09-08 21:46:05.222009033,"[1.3960937479253839, 0.6537273699603849, 0.435..."
14,1.725832e+09,-0.0,"[-0.03259311, -0.03640294, -0.0145734865, 0.02...","[-0.03259311, -0.03640294, -0.0145734865, 0.02...",2024-09-08 21:46:05.327989990,"[1.3951038846253143, 0.652525325610753, 0.4354..."